POST http://{{host}}/multi-query-test/mock-resources/some-resource?foo=5
Content-Type: application/json

{
  "responseBody": "response payload foo",
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###

POST http://{{host}}/multi-query-test/mock-resources/some-resource?bar=10
Content-Type: application/json

{
  "responseBody": "response payload bar",
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###

POST http://{{host}}/multi-query-test/mock-resources/some-resource?a=1&b=2&b=3
Content-Type: application/json

{
  "responseBody": "response payload a b",
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###

POST http://{{host}}/multi-query-test/mock-resources/some-resource?a=2&b=4&b=6
Content-Type: application/json

{
  "responseBody": "response payload aa bb",
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###

PUT http://{{host}}/multi-query-test/some-resource?foo=5
Content-Type: text/plain

FOO

###

PUT http://{{host}}/multi-query-test/some-resource?bar=10
Content-Type: text/plain

BAR

###

PUT http://{{host}}/multi-query-test/some-resource?a=1&b=2&b=3
Content-Type: text/plain

A B

###

PUT http://{{host}}/multi-query-test/some-resource?b=2&a=1&b=3
Content-Type: text/plain

B A

###

PUT http://{{host}}/multi-query-test/some-resource?a=2&b=4&b=6
Content-Type: text/plain

AA BB

###

GET http://{{host}}/multi-query-test/some-resource?a=2&b=6&b=4

###

GET http://{{host}}/multi-query-test/some-resource?a=1&b=3

###

GET http://{{host}}/multi-query-test/some-resource?foo=6

###

GET http://{{host}}/multi-query-test/some-resource/mock-resources?foo=5

###


GET http://{{host}}/multi-query-test/some-resource/mock-resources?bar=10

###

GET http://{{host}}/multi-query-test/some-resource/mock-resources?a=1&b=2&b=3

###

GET http://{{host}}/multi-query-test/some-resource/mock-resources?b=2&a=1&b=3

###

GET http://{{host}}/multi-query-test/some-resource/mock-resources?b=4&a=2&b=6

###

GET http://{{host}}/multi-query-test/some-resource/mock-resources?b=4&a=2&b=6&verifyMockContent=list

###

GET http://{{host}}/multi-query-test/some-resource/mock-resources?b=4&a=2&b=6&verifyMockContent=last

###

GET http://{{host}}/multi-query-test/some-resource/mock-resources?b=4&a=2&b=6&verifyMockContent=detailed
###
