POST http://{{host}}/x-request-id-example/mock-resources
X-Request-ID: abc
Content-Type: application/json

{
  "responseBody": {
    "data": "X-Request-ID: abc"
  },
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###

POST http://{{host}}/x-request-id-example
X-Request-ID: abc
Content-Type: application/json

{
  "thing": 1
}

###

POST http://{{host}}/x-request-id-example
X-Request-ID: abc
Content-Type: application/json

{
  "thing": 2
}

###

POST http://{{host}}/x-request-id-example/mock-resources
X-Request-ID: abcd
Content-Type: application/json

{
  "responseBody": {
    "data": "X-Request-ID: abcd"
  },
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###


POST http://{{host}}/x-request-id-example
X-Request-ID: abcd
Content-Type: application/json

{
  "thing2": 5
}

###

GET http://{{host}}/x-request-id-example/mock-resources
X-Request-ID: abc

###

GET http://{{host}}/x-request-id-example/mock-resources
X-Request-ID: abcd

###

GET http://{{host}}/x-request-id-example/mock-resources

###

POST http://{{host}}/x-request-id-example/mock-resources
X-Header-A: abc
X-Header-B: def
Content-Type: application/json

{
  "responseBody": {
    "data": "X-Request-ID: abc,X-Header-B: def"
  },
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###

POST http://{{host}}/x-request-id-example/mock-resources
X-Header-A: abc
X-Header-B: defg
Content-Type: application/json

{
  "responseBody": {
    "data": "X-Request-ID: abc,X-Header-B: defg"
  },
  "responseSetUpMetadata": {
    "delayMs": 0,
    "httpStatus": 200
  }
}

###

POST http://{{host}}/x-request-id-example
X-Header-A: abc
X-Header-B: def
Content-Type: application/json

{
  "thing": 1
}

###

POST http://{{host}}/x-request-id-example
X-Header-A: abc
X-Header-B: defg
Content-Type: application/json

{
  "thing": 1
}

###

GET http://{{host}}/x-request-id-example/mock-resources
X-Header-A: abc
X-Header-B: def

###

GET http://{{host}}/x-request-id-example/mock-resources
X-Header-A: abc
X-Header-B: defg

###
